name: test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2

      - name: Install Tuist
        run: mise install tuist@4.10.0
      
      - name: Tuist activation
        run: mise use -g tuist@4.10.0

      - name: Run tests
        run: tuist test --no-binary-cache